            LST   OFF
            TR
            TR    ADR

            REL
            DSK   REL/INITSTR

*-------------------------------
* init strings for modems
*-------------------------------

usr2400     ENT
            ASC   'ATX2S0=0S2=128E0V0F1Q0'0d00

usr9600     ENT
            ASC   'ATX6&S1&D2V0S0=0S2=128E0F1Q0'0d00

cts         ENT
            ASC   'ATX3S0=0S2=128V0E0F1Q0&C1&D2S10=3'0D00

apl1200     ENT
            ASC   'ATX1S0=0S2=128V0'0D00

hayes1200   ENT
            ASC   'ATS0=0S2=128S18=0V0'0D00

hayes2400   ENT
            ASC   'ATX3S0=0&C1&D2S2=128V0'0D00

pro2400     ENT
            ASC   'ATX5S0=0S2=128V0'0D00

generic     ENT
            ASC   'ATS0=0S2=128V0'0D00

epic        ENT
            ASC   'ATS0=0S2=128&S1&D2V0'0D00

