            TTL   'LLUCE - Entry Points'
            PAG
VIDRDKY     =     $F00
VIDSTORE    =     $F03
VIDCOUT     =     $F06
VIDSCRL     =     $F09
VIDBAN      =     $F0C
VIDLST      =     $F0F
VIDRDST     =     $F12
VIDPOS      =     $F15
VIDCHAT     =     $F18

GETBYT      =     $F100
CHKBYT      =     $F103
GOBCOM      =     $F106
INPNUM      =     $F109
INPSTR      =     $F10C
INPNARG     =     $F10F
INPSARG     =     $F112
ZNUMIN      =     $F115
DO_MATH     =     $F118
MOVNAME     =     $F11B
BADERR      =     $F11E

SETIVEC     =     $F121
CHKKEY      =     $F124
GETCHR      =     $F127
INPLN       =     $F12A
RDKEY       =     $F12D

SETOVEC     =     $F130
COUT        =     $F133
DECOUT0     =     $F136
DO_SED      =     $F139

PD_MAKE     =     $F13C
PD_KILL     =     $F13F
PD_OPEN     =     $F142
IFOPEN      =     $F145
PD_CLOSE    =     $F148
PD_FLUSH    =     $F14B
PD_RDBYT    =     $F14E
PD_WRBYT    =     $F151
PD_RDBLK    =     $F154
PD_WRBLK    =     $F157
PD_RDLN     =     $F15A
PD_GMARK    =     $F15D
PD_SPOS     =     $F160
PD_GPFX     =     $F163
PD_SPFX     =     $F166
LOGSYS      =     $F169
NOLABEL     =     $F16C
SHOWSTR     =     $F16F
PD_NEWLN    =     $F172

ED_CLR      =     $F175
EDIN        =     $F178
EDOUT       =     $F17B
ADDCRC      =     $F17E

PD_RBYTS    =     $F181
PD_WBYTS    =     $F184

SYSSTORE    =     $F187
SYSRCAL     =     $F18A

COMPRES     =     $F18D                   ; Compress Variables
UNCOMP      =     $F190                   ; Un-Compress Variables
RELOAD      =     $F193                   ; Reload segment
DO_CL3      =     $F196

TOFLN       =     $F199                   ; Move string (X,A) to fn
FRMFLN      =     $F19C                   ; Move fn to string (X,A)

WHATSTK     =     $F1E0                   32

