            LST   RTN
            TTL   'LLUCE - Error codes'
            PAG
*-------------------------------
* Error codes

Syntax      =     1
Prgend      =     2
Misssym     =     3
Missdata    =     4
Typemiss    =     5
Strtobig    =     6
Numtobig    =     7
Divby0      =     8
Baddev      =     9
Badfn       =     $A
Linknf      =     $B
Msgnf       =     $C
Badxtrn     =     $D
Badpfx      =     $E
Modulenf    =     $F
Badwrite    =     $10
Undeflbl    =     $11
Gsbfull     =     $12
Nogosub     =     $13
Forfull     =     $14
Nonext      =     $15
Noerr       =     $16
Badver      =     $17
SysTerm     =     $18
DoFull      =     $19
NoDo        =     $1A
WhileFul    =     $1B
Usrerr      =     $1C

SMnotFnd    =     1
Moment1     =     2
ExecOut     =     3
SysopIn     =     4
SysopOut    =     5
TimedOut    =     6
Moment2     =     7
MomntOut    =     8
            LST   OFF

